name: UnderGround Command
favicon: null
layout_spectrum: 1
typography_spectrum: 1
title: UnderGround Command
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.07365136756561697
  lightness: 0.8866754835471511
  saturation: 0.7339703636243939
  rhythmicContrast: 0.5970600370783359
purpose: []
